import { ActivityItem, AppUser, Ticket, TicketActivity, TicketMessage } from "@/lib/types";

export const users: AppUser[] = [
  {
    id: "u1",
    name: "Unarine Luvhimbi",
    email: "unarine@example.com",
    role: "end_user",
  },
  {
    id: "u2",
    name: "Naledi Maseko",
    email: "naledi@example.com",
    role: "end_user",
  },
  {
    id: "s1",
    name: "Ava Support",
    email: "ava.support@example.com",
    role: "support",
    team: "End User Support",
  },
  {
    id: "s2",
    name: "Neo Security",
    email: "neo.security@example.com",
    role: "support",
    team: "Security Operations",
  },
  {
    id: "a1",
    name: "Admin Control",
    email: "admin@example.com",
    role: "admin",
    team: "Operations Control",
  },
];

export const sampleAnalysisSteps = [
  "Parsing issue context",
  "Detecting affected services",
  "Scoring urgency and business impact",
  "Mapping best-fit support team",
  "Preparing structured response",
];

export const tickets: Ticket[] = [
  {
    id: "TICK-1001",
    ownerId: "u1",
    ownerName: "Unarine Luvhimbi",
    originalMessage: "I cannot access Outlook and Teams on my laptop. It keeps asking me to sign in again and nothing syncs.",
    summary: "User cannot access Outlook and Teams on laptop and is stuck in repeated sign-in prompts.",
    category: "Email / Collaboration",
    priority: "High",
    routedTeam: "End User Support",
    status: "Analyzed",
    securityFlag: false,
    createdAt: "2026-03-20T09:15:00Z",
    analysis: {
      summary: "User cannot access Outlook and Teams on laptop and is stuck in repeated sign-in prompts.",
      category: "Email / Collaboration",
      priority: "High",
      routedTeam: "End User Support",
      impactedServices: ["Outlook", "Teams", "Microsoft 365 Sign-In"],
      securityFlag: false,
      confidence: 0.93,
      recommendedActions: [
        "Verify internet connectivity and Microsoft 365 service health",
        "Check local account token/session state on the device",
        "Confirm whether the issue is isolated to a single endpoint",
      ],
      draftResponse: "We’ve identified this as a high-priority collaboration access issue. Please confirm whether this affects only your laptop and share any Outlook or Teams error messages you can see.",
    },
  },
  {
    id: "TICK-1002",
    ownerId: "u2",
    ownerName: "Naledi Maseko",
    originalMessage: "I clicked a suspicious email link and now my laptop is acting weird. Browser opened strange tabs.",
    summary: "User clicked a suspicious email link and reports abnormal device behavior.",
    category: "Security Incident",
    priority: "Critical",
    routedTeam: "Security Operations",
    status: "In Progress",
    securityFlag: true,
    createdAt: "2026-03-20T09:32:00Z",
    analysis: {
      summary: "User clicked a suspicious email link and reports abnormal device behavior.",
      category: "Security Incident",
      priority: "Critical",
      routedTeam: "Security Operations",
      impactedServices: ["Email", "Browser", "Endpoint Device"],
      securityFlag: true,
      confidence: 0.98,
      recommendedActions: [
        "Disconnect affected device from network if possible",
        "Escalate immediately to Security Operations",
        "Collect phishing email details and preserve browser/session evidence",
      ],
      draftResponse: "This has been identified as a critical security incident and has been escalated immediately. Please stop using the affected device, disconnect it from the network if possible, and avoid interacting further with the suspicious email.",
    },
  },
  {
    id: "TICK-1003",
    ownerId: "u1",
    ownerName: "Unarine Luvhimbi",
    originalMessage: "Please install Adobe Acrobat on my company laptop for contract review work.",
    summary: "User is requesting Adobe Acrobat installation on work laptop.",
    category: "Service Request",
    priority: "Low",
    routedTeam: "End User Support",
    status: "New",
    securityFlag: false,
    createdAt: "2026-03-20T10:02:00Z",
    analysis: {
      summary: "User is requesting Adobe Acrobat installation on work laptop.",
      category: "Service Request",
      priority: "Low",
      routedTeam: "End User Support",
      impactedServices: ["Adobe Acrobat", "Endpoint Device"],
      securityFlag: false,
      confidence: 0.9,
      recommendedActions: [
        "Confirm software entitlement or approved license path",
        "Validate device compatibility before deployment",
      ],
      draftResponse: "Your software installation request has been logged and routed to End User Support. They will confirm licensing and device compatibility before proceeding.",
    },
  },
  {
    id: "TICK-1004",
    ownerId: "u2",
    ownerName: "Naledi Maseko",
    originalMessage: "Several users on our floor cannot get onto the VPN this morning.",
    summary: "Multiple users are unable to connect to VPN, indicating a wider connectivity issue.",
    category: "Network / Connectivity",
    priority: "Critical",
    routedTeam: "Network Support",
    status: "Analyzed",
    securityFlag: false,
    createdAt: "2026-03-20T10:17:00Z",
    analysis: {
      summary: "Multiple users are unable to connect to VPN, indicating a wider connectivity issue.",
      category: "Network / Connectivity",
      priority: "Critical",
      routedTeam: "Network Support",
      impactedServices: ["VPN", "Remote Access Gateway"],
      securityFlag: false,
      confidence: 0.95,
      recommendedActions: [
        "Validate whether outage is region- or floor-specific",
        "Check VPN concentrator health and authentication dependencies",
        "Publish incident communication if disruption continues",
      ],
      draftResponse: "We’ve identified this as a critical connectivity issue affecting multiple users and have routed it to Network Support for urgent investigation.",
    },
  },
];

export const ticketMessages: TicketMessage[] = [
  {
    id: "M-1001-1",
    ticketId: "TICK-1001",
    senderId: "system",
    senderName: "System",
    senderRole: "system",
    visibility: "system",
    body: "Ticket created and AI analysis completed.",
    createdAt: "2026-03-20T09:15:03Z",
  },
  {
    id: "M-1001-2",
    ticketId: "TICK-1001",
    senderId: "s1",
    senderName: "Ava Support",
    senderRole: "support",
    visibility: "public",
    body: "Please confirm whether this affects only your laptop and share the exact sign-in error text if you can.",
    createdAt: "2026-03-20T09:18:00Z",
  },
  {
    id: "M-1001-3",
    ticketId: "TICK-1001",
    senderId: "u1",
    senderName: "Unarine Luvhimbi",
    senderRole: "user",
    visibility: "public",
    body: "Yes, it is only affecting my laptop. Outlook says sign-in required and Teams keeps looping.",
    createdAt: "2026-03-20T09:20:00Z",
  },
  {
    id: "M-1001-4",
    ticketId: "TICK-1001",
    senderId: "s1",
    senderName: "Ava Support",
    senderRole: "support",
    visibility: "internal",
    body: "Potential token/session corruption on local Microsoft 365 profile. Check device-specific cache and auth state.",
    createdAt: "2026-03-20T09:22:00Z",
  },
  {
    id: "M-1002-1",
    ticketId: "TICK-1002",
    senderId: "system",
    senderName: "System",
    senderRole: "system",
    visibility: "system",
    body: "Critical security incident detected and routed to Security Operations.",
    createdAt: "2026-03-20T09:32:10Z",
  },
  {
    id: "M-1002-2",
    ticketId: "TICK-1002",
    senderId: "s2",
    senderName: "Neo Security",
    senderRole: "support",
    visibility: "public",
    body: "Please disconnect the affected device from the network if possible and avoid interacting with the suspicious email any further.",
    createdAt: "2026-03-20T09:33:00Z",
  },
  {
    id: "M-1002-3",
    ticketId: "TICK-1002",
    senderId: "s2",
    senderName: "Neo Security",
    senderRole: "support",
    visibility: "internal",
    body: "Escalate to endpoint investigation. Preserve browser and mailbox evidence.",
    createdAt: "2026-03-20T09:34:00Z",
  },
  {
    id: "M-1003-1",
    ticketId: "TICK-1003",
    senderId: "system",
    senderName: "System",
    senderRole: "system",
    visibility: "system",
    body: "Ticket created and queued for End User Support.",
    createdAt: "2026-03-20T10:02:20Z",
  },
  {
    id: "M-1004-1",
    ticketId: "TICK-1004",
    senderId: "system",
    senderName: "System",
    senderRole: "system",
    visibility: "system",
    body: "Multiple-user impact detected. Priority elevated to Critical.",
    createdAt: "2026-03-20T10:17:05Z",
  },
];

export const ticketActivities: TicketActivity[] = [
  {
    ticketId: "TICK-1001",
    actionType: "ticket_created",
    actionDetails: "Ticket created from incoming support request.",
    createdAt: "2026-03-20T09:15:00Z",
    visibility: "public",
  },
  {
    ticketId: "TICK-1001",
    actionType: "analysis_completed",
    actionDetails: "AI analysis completed successfully with structured output.",
    createdAt: "2026-03-20T09:15:03Z",
    visibility: "internal",
  },
  {
    ticketId: "TICK-1001",
    actionType: "routed_to_team",
    actionDetails: "Ticket routed to End User Support.",
    createdAt: "2026-03-20T09:15:05Z",
    visibility: "public",
  },
  {
    ticketId: "TICK-1002",
    actionType: "escalated",
    actionDetails: "Security incident escalated to Security Operations.",
    createdAt: "2026-03-20T09:32:15Z",
    visibility: "internal",
  },
  {
    ticketId: "TICK-1004",
    actionType: "analysis_completed",
    actionDetails: "Agent classified request as Network / Connectivity with Critical priority.",
    createdAt: "2026-03-20T10:17:05Z",
    visibility: "internal",
  },
];

export const activityFeed: ActivityItem[] = [
  {
    ticketId: "TICK-1004",
    actionType: "analysis_completed",
    actionDetails: "Agent classified request as Network / Connectivity with Critical priority.",
    createdAt: "2026-03-20T10:17:05Z",
  },
  {
    ticketId: "TICK-1002",
    actionType: "escalated",
    actionDetails: "Security incident escalated to Security Operations.",
    createdAt: "2026-03-20T09:32:15Z",
  },
  {
    ticketId: "TICK-1001",
    actionType: "routed_to_team",
    actionDetails: "Ticket routed to End User Support.",
    createdAt: "2026-03-20T09:15:09Z",
  },
];

export const dashboardStats = {
  totalTickets: tickets.length,
  highPriority: tickets.filter((ticket) => ticket.priority === "High").length,
  criticalIssues: tickets.filter((ticket) => ticket.priority === "Critical").length,
  activeRequests: tickets.filter((ticket) => ticket.status !== "Resolved").length,
};
